if isfile('mea.config')
    T = readtable('mea.config', ...
        'FileType', 'delimitedtext', ...
        'NumHeaderLines', 0, ...
        'ReadRowNames', true, ...
        'delimiter',':', ...
        'CommentStyle','#');

    S = rmfield(table2struct(rows2vars(T)), ...
        'OriginalVariableNames');
end

fprintf('MEA: %s\n', S.MEA);

fprintf('Syscal: %s\n', S.Syscal);

% % 'ReadVariableNames', false, ...